package homework7;

/**
 *
 * @author Danny Jimenez
 */
public class Principal extends javax.swing.JFrame {
    private int xx,yy;
    private String[] identificadores = new String[3];
    private int contador = 1;
    
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mError = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jEPanel = new javax.swing.JPanel();
        bAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mCorrecto = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jCPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pDebajo = new javax.swing.JPanel();
        pSobre = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        bTercero = new javax.swing.JButton();
        bPrimero = new javax.swing.JButton();
        bSegundo = new javax.swing.JButton();
        bExit = new javax.swing.JButton();

        mError.setAlwaysOnTop(true);
        mError.setLocationByPlatform(true);
        mError.setMinimumSize(new java.awt.Dimension(514, 168));
        mError.setModal(true);
        mError.setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jEPanel.setBackground(new java.awt.Color(0, 102, 102));
        jEPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 4, new java.awt.Color(255, 255, 255)));
        jEPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jEPanelMouseDragged(evt);
            }
        });
        jEPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jEPanelMousePressed(evt);
            }
        });

        bAceptar.setBackground(new java.awt.Color(0, 153, 153));
        bAceptar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bAceptar.setForeground(new java.awt.Color(255, 255, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("homework7/Bundle"); // NOI18N
        bAceptar.setText(bundle.getString("Principal.bAceptar.text")); // NOI18N
        bAceptar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(255, 255, 255)));
        bAceptar.setContentAreaFilled(false);
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("Principal.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jEPanelLayout = new javax.swing.GroupLayout(jEPanel);
        jEPanel.setLayout(jEPanelLayout);
        jEPanelLayout.setHorizontalGroup(
            jEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEPanelLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(jEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jEPanelLayout.setVerticalGroup(
            jEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mErrorLayout = new javax.swing.GroupLayout(mError.getContentPane());
        mError.getContentPane().setLayout(mErrorLayout);
        mErrorLayout.setHorizontalGroup(
            mErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mErrorLayout.setVerticalGroup(
            mErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mCorrecto.setAlwaysOnTop(true);
        mCorrecto.setLocationByPlatform(true);
        mCorrecto.setMinimumSize(new java.awt.Dimension(445, 168));
        mCorrecto.setModal(true);
        mCorrecto.setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jCPanel.setBackground(new java.awt.Color(0, 102, 102));
        jCPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 4, new java.awt.Color(255, 255, 255)));
        jCPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jCPanelMouseDragged(evt);
            }
        });
        jCPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCPanelMousePressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText(bundle.getString("Principal.jButton2.text")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(255, 255, 255)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(bundle.getString("Principal.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout jCPanelLayout = new javax.swing.GroupLayout(jCPanel);
        jCPanel.setLayout(jCPanelLayout);
        jCPanelLayout.setHorizontalGroup(
            jCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCPanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCPanelLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(148, 148, 148))
        );
        jCPanelLayout.setVerticalGroup(
            jCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mCorrectoLayout = new javax.swing.GroupLayout(mCorrecto.getContentPane());
        mCorrecto.getContentPane().setLayout(mCorrectoLayout);
        mCorrectoLayout.setHorizontalGroup(
            mCorrectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mCorrectoLayout.setVerticalGroup(
            mCorrectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setUndecorated(true);

        pDebajo.setBackground(new java.awt.Color(102, 102, 102));

        pSobre.setBackground(new java.awt.Color(0, 153, 153));
        pSobre.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 5, 5, new java.awt.Color(255, 255, 255)));
        pSobre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pSobreMouseDragged(evt);
            }
        });
        pSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pSobreMousePressed(evt);
            }
        });

        lTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText(bundle.getString("Principal.lTitulo.text")); // NOI18N

        bTercero.setBackground(new java.awt.Color(0, 102, 102));
        bTercero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bTercero.setForeground(new java.awt.Color(255, 255, 255));
        bTercero.setText(bundle.getString("Principal.bTercero.text")); // NOI18N
        bTercero.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 3, new java.awt.Color(255, 255, 255)));
        bTercero.setContentAreaFilled(false);
        bTercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTerceroActionPerformed(evt);
            }
        });

        bPrimero.setBackground(new java.awt.Color(0, 102, 102));
        bPrimero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bPrimero.setForeground(new java.awt.Color(255, 255, 255));
        bPrimero.setText(bundle.getString("Principal.bPrimero.text")); // NOI18N
        bPrimero.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 3, new java.awt.Color(255, 255, 255)));
        bPrimero.setContentAreaFilled(false);
        bPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrimeroActionPerformed(evt);
            }
        });

        bSegundo.setBackground(new java.awt.Color(0, 102, 102));
        bSegundo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bSegundo.setForeground(new java.awt.Color(255, 255, 255));
        bSegundo.setText(bundle.getString("Principal.bSegundo.text")); // NOI18N
        bSegundo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 3, new java.awt.Color(255, 255, 255)));
        bSegundo.setContentAreaFilled(false);
        bSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSegundoActionPerformed(evt);
            }
        });

        bExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework7/exit.png"))); // NOI18N
        bExit.setMnemonic('x');
        bExit.setText(bundle.getString("Principal.bExit.text")); // NOI18N
        bExit.setBorder(null);
        bExit.setBorderPainted(false);
        bExit.setContentAreaFilled(false);
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSobreLayout = new javax.swing.GroupLayout(pSobre);
        pSobre.setLayout(pSobreLayout);
        pSobreLayout.setHorizontalGroup(
            pSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSobreLayout.createSequentialGroup()
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSobreLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(bSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(bTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSobreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pSobreLayout.setVerticalGroup(
            pSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(pSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout pDebajoLayout = new javax.swing.GroupLayout(pDebajo);
        pDebajo.setLayout(pDebajoLayout);
        pDebajoLayout.setHorizontalGroup(
            pDebajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDebajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDebajoLayout.setVerticalGroup(
            pDebajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDebajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDebajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTerceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTerceroActionPerformed
        if(contador == 3){
           identificadores[2] = "3";
           finalizar();
       }
       else{
            contador++;
            identificadores[0] = "X";
       }
    }//GEN-LAST:event_bTerceroActionPerformed

    private void bSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSegundoActionPerformed
        if(contador == 3){
           finalizar();
       }
       else{
           if(contador == 2){
               contador++;
               identificadores[0] = "2";
           }else{
               contador++;
               identificadores[0] = "X";
           }
       }
    }//GEN-LAST:event_bSegundoActionPerformed

    private void bPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrimeroActionPerformed
       if(contador == 3){
           finalizar();
       }
       else{
           if(contador == 1){
               contador++;
               identificadores[0] = "1";
           }else{
               contador++;
               identificadores[0] = "X";
           }
       }
       
    }//GEN-LAST:event_bPrimeroActionPerformed
    
    private void pSobreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSobreMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_pSobreMousePressed

    private void pSobreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSobreMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xx,y-yy);
    }//GEN-LAST:event_pSobreMouseDragged

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        this.setVisible(true);
        mError.setVisible(false);
    }//GEN-LAST:event_bAceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(true);
        mCorrecto.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jEPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEPanelMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jEPanelMousePressed

    private void jEPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEPanelMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
        
       mError.setLocation(x-xx,y-yy);
    }//GEN-LAST:event_jEPanelMouseDragged

    private void jCPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCPanelMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jCPanelMousePressed

    private void jCPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCPanelMouseDragged
        int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
        
       mCorrecto.setLocation(x-xx,y-yy);
    }//GEN-LAST:event_jCPanelMouseDragged
                                 
    private void finalizar(){
        int prueba;
        try{
            for(int i = 0; i < identificadores.length; i++){
                prueba = Integer.parseInt(identificadores[0]);
            }
            contador = 1;
            mCorrecto.setVisible(true);
            
            
        }catch( NumberFormatException e){
            mError.setVisible(true);
            contador = 1;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Principal principal = new Principal();
        principal.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bAceptar;
    public javax.swing.JButton bExit;
    public javax.swing.JButton bPrimero;
    public javax.swing.JButton bSegundo;
    public javax.swing.JButton bTercero;
    public javax.swing.JButton jButton2;
    public javax.swing.JPanel jCPanel;
    public javax.swing.JPanel jEPanel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lTitulo;
    public javax.swing.JDialog mCorrecto;
    public javax.swing.JDialog mError;
    public javax.swing.JPanel pDebajo;
    public javax.swing.JPanel pSobre;
    // End of variables declaration//GEN-END:variables
}
